# Quarkus HTTP port (optional)
quarkus.http.port=8080
# Enable detailed exception mapping in dev
quarkus.http.access-log.enabled=true
quarkus.log.console.format="%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"